<!doctype html>
<html>
<head>
<meta charset="utf-8">
<!--script src="http://code.jquery.com/jquery-1.11.2.min.js"></script-->
<!--script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script-->
<!--script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script-->
<!--link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css"-->
<script src="/jquery/jquery-1.11.2.min.js"></script>
<script src="/jquery/jquery-ui-1.11.4.custom/jquery-ui.min.js"></script>
<link rel="stylesheet" href="/jquery/jquery-ui-1.11.4.custom/jquery-ui.min.css">
<link rel="stylesheet" href="/jquery/jquery-ui-1.11.4.custom/jquery-ui.theme.css">
<!----- jMenu ---->
<link rel="stylesheet" type="text/css" href="/jMenu/css/jmenu.css" media="screen" />
<script type="text/javascript" src="/jMenu/js/jMenu.jquery.min.js"></script>
<!----- 自己開發的 js Library ----->
<script src="/jslib/ajaxIdSelector.js" ></script>
<script src="/jslib/HGrid.js" ></script>
